name: Deploy Application

on:
  push:
    branches:
      - main

env:
  IMAGE_BASE_NAME: ElsAppImage
  KEY_VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
  KEY_VAULT_SECRET_NAME_ACR_USERNAME: ElsACRUsername
  KEY_VAULT_SECRET_NAME_ACR_PASSWORD: ElsACRPassword

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Docker Registry Credentials from Azure Key Vault
        uses: azure/CLI@v1
        with:
          inlineScript: |
            REGISTRY_USERNAME=$(az keyvault secret show --name $KEY_VAULT_SECRET_NAME_ACR_USERNAME --vault-name $KEY_VAULT_NAME --query value -o tsv)
            REGISTRY_PASSWORD=$(az keyvault secret show --name $KEY_VAULT_SECRET_NAME_ACR_PASSWORD --vault-name $KEY_VAULT_NAME --query value -o tsv)
            echo "REGISTRY_USERNAME=${REGISTRY_USERNAME}" >> $GITHUB_ENV
            echo "REGISTRY_PASSWORD=${REGISTRY_PASSWORD}" >> $GITHUB_ENV

      - name: Set Image Version
        id: image-version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')"

      - name: Build and Push Image
        working-directory: ./app
        run: |
          docker login ElsACR123.azurecr.io -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          docker build . -t ElsACR123.azurecr.io/ElsAppImage:${{ steps.image-version.outputs.version }}
          docker push ElsACR123.azurecr.io/ElsAppImage:${{ steps.image-version.outputs.version }}
          docker build . -t ElsACR123.azurecr.io/ElsAppImage:latest
          docker push ElsACR123.azurecr.io/ElsAppImage:latest

  deploy-to-webapp:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ElsWebApp"
          images: "ElsACR123.azurecr.io/ElsAppImage:${{ steps.image-version.outputs.version }}"
